In [2]:
import numpy as np
import matplotlib.pyplot as plt


xvals = (0,1,2)
sigmavals = (0.1,0.1,0.1)
npar = 3

F = np.zeros([npar,npar])
r0 = 1
I0 = 1

In [3]:
for x,sigma in zip(xvals,sigmavals):
    for i in range(npar):
        if i == 0:
            dfdpi = np.exp(-x)
        elif i == 1:
            dfdpi = 1
        else:
            dfdpi =  I0*x*np.exp(-x)/r0
        for j in range(npar):
            if j == 0:
                dfdpj = np.exp(-x)
            elif j == 1:
                dfdpj = 1
            else:
                dfdpj = I0*x*np.exp(-x)/r0
            F[i,j] += (1/sigma**2)*dfdpi*dfdpj

print("Fisher information matrix: ")
print(F)

print("Covariance matrix: ")
print(np.mat(F).I)

Fisher information matrix: 
[[115.36509221 150.32147244  17.1966561 ]
 [150.32147244 300.          63.85500076]
 [ 17.1966561   63.85500076  20.85978388]]
Covariance matrix: 
[[ 0.1009114  -0.09429837  0.20547115]
 [-0.09429837  0.09768534 -0.22129091]
 [ 0.20547115 -0.22129091  0.55595565]]


adding prior information to parameter b

In [4]:
prior_b = 2
F[1,1] += 1/prior_b**2

print("Fisher information matrix: ")
print(F)

print("Covariance matrix: ")
print(np.mat(F).I)

Fisher information matrix: 
[[115.36509221 150.32147244  17.1966561 ]
 [150.32147244 300.25        63.85500076]
 [ 17.1966561   63.85500076  20.85978388]]
Covariance matrix: 
[[ 0.09874135 -0.09205037  0.20037867]
 [-0.09205037  0.0953566  -0.21601553]
 [ 0.20037867 -0.21601553  0.54400508]]
